branch-defaults:
  main:
    environment: mpp-backend-env
global:
  application_name: mpp-backend
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application 